change invalid character list, campatible with non-latin characters
amaiorano/md-to-toc pull request #4
Opened 2017-12-25 12:38 UTC by haiwenzhu

This commit is aim to campatible with non-latin character like Chinese.

2017-12-26 18:53 UTC, amaiorano commented on md-to-toc.py
> +    anchor_name = re.sub("[\]\[\!\"\#\$\%\&\'\(\)\*\+\,\.\/\:\;\<\=\>\?\@\\\^\_\{\|\}\~]", "", anchor_name)
This is a useful change, but could we make this code more clear by using Python raw strings here? Could you try with:

```python
    anchor_name = re.sub(r"[][!"#$%&'()*+,./:;<=>?@\^_{|}~]", "", anchor_name)
```

I haven't tested this, but I assume it should give the same result.

2017-12-26 18:54 UTC, amaiorano requested changes
Let's try with the raw string. If that works, please update the PR. I'll merge one of these in any case. Thanks!

2017-12-27 09:00 UTC, haiwenzhu commented
Thanks for your suggestion, i tried raw string, it works with following
```python
anchor_name = re.sub(r"[\[\]\"!#$%&'()*+,./:;<=>?@\^_{|}~]", "", anchor_name)
```
And i have pushed the new change.

2017-12-27 15:29 UTC, merged

2017-12-27 15:29 UTC, amaiorano commented
Thanks!